version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: elasticsearch
    restart: always
    environment:
      discovery.type: single-node
    volumes:
      - /data/elk/elasticsearch/data:/usr/share/elasticsearch/data
      - /data/elk/elasticsearch/certificate:/usr/share/elasticsearch/certificate
      - /data/elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.2
    container_name: logstash
    restart: always
    depends_on:
      - elasticsearch
    volumes:
      - /data/elk/logstash/pipeline:/usr/share/logstash/pipeline
      - /data/elk/log:/var/log

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.2
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
